#!/bin/sh

# random stuff
alias webm='ffmpeg -f x11grab -s 1366x768 -an -r 16 -loglevel quiet -i :0.0 -b:v 5M -y screen_record.webm'
alias wm='exec bwm'
alias xd='xrdb -load $HOME/.Xresources'
alias keys='killall xbindkeys && xbindkeys'
alias lab='ssh -X spinto@linux.csc.uvic.ca'
alias al='vim $HOME/shell/aliases'
alias -g S='| curl -F "sprunge=<-" http://sprunge.us'
alias v='vim'
alias m='ncmpcpp'

# utils
alias ls='ls -F --color=auto'
alias la='ls -FA'
alias lf='ls -Ft |head -n6'
alias ll='ls -ahlF'
alias la='ls -A'
alias g='ls -A | grep -i'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias du='du -sh'
alias df='df -h'
alias p='pwd'
alias ..='cd ..'

# git
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push origin master'
alias gb='git checkout -b new_branch'
alias gl='git log --decorate --pretty=oneline --abbrev-commit --graph'
alias gd='git diff'

# pacman
alias q='pacman -Q|grep -i'
alias r='sudo pacman -Rsn'
alias i='sudo pacman -S'
alias s='pacman -Ss'
alias u='sudo pacman -Syu'
