#!/bin/sh

# common
alias ns='npm start'
alias smi='sudo make clean install'
alias md='make clean debug'
alias al='vim ~/shell_aliases'
alias fu='vim ~/shell_functions'
alias xd='xrdb -load ~/.Xresources'
alias v='vim'
alias e='emacs -nw'
alias n='ncmpcpp'

# random stuff
alias wifi='netctl restart wlp8s0-NETGEAR21'
alias flib='find /usr/include -name '
alias webcam='mpv /dev/video0'
alias keys='killall xbindkeys && xbindkeys'
alias -g S='| curl -F "sprunge=<-" http://sprunge.us'
alias g='la | grep -i '
alias s='sudo !!'

# utils
alias ls='ls -F --color=auto'
alias ll='ls -ahlF'
alias la='ls -FA'
alias a='la'
alias c='cd'
alias grep='grep --color=auto'
alias du='du -sh'
alias df='df -h'
alias less='less -R'
alias tree='tree -I node_modules'
alias define='sdcv'
# alias ag='ag --nogroup --color-path "0;35" --color-match "1;31" --nonumbers -U --hidden'
alias feh='feh -q'

# git
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gb='git branch'
alias gco='git checkout'
alias gp='git push'
alias gl='git log --decorate --name-only'
alias gd='git diff'
alias gdl='git diff HEAD~1 HEAD'
alias gr='git remote -v'

# pacman
alias pacq='pacman -Q|grep -i'
alias pacr='sudo pacman -Rsn'
alias paci='sudo pacman -S'
alias pacs='pacman -Ss'
alias u='sudo pacman -Syu'

# systemd
alias sc='systemctl'
alias jc='journalctl'
alias nc='netctl'
alias st='systemctl status'
