#!/bin/sh

# random stuff
alias tree='tree -I node_modules'
alias define='sdcv'
alias flib='find /usr/include -name '
# alias wifi='sudo ip link set wlp8s0 up'
alias ag='ag --nogroup --color-path "0;35" --color-match "1;31" --nonumbers -U --hidden'
alias smi='sudo make install'
alias rand='feh --bg-scale -z ~/pictures/walls'
alias wi='wicd-curses'
alias webcam='mpv /dev/video0'
alias xm='xrdb -merge'
alias keys='killall xbindkeys && xbindkeys'
alias al='vim $HOME/shell_aliases'
alias v='vim'
alias m='ncmpcpp'
alias -g S='| curl -F "sprunge=<-" http://sprunge.us'
alias startx='ssh-agent startx'

# utils
alias ls='ls -F --color=auto'
alias la='ls -FA'
alias a='la'
alias ll='ls -ahlF'
alias grep='grep --color=auto'
alias du='du -sh'
alias df='df -h'
alias g='la | grep -i '
# alias s='sudo'
alias x='chmod +x'
alias less='less -R'

# git
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gb='git branch'
alias gco='git checkout'
alias gp='git push'
alias gl='git log --decorate --name-only'
alias gd='git diff'
alias gdl='git diff HEAD~1 HEAD'
alias gr='git remote -v'

# pacman
alias pacq='pacman -Q|grep -i'
alias pacr='sudo pacman -Rssn'
alias paci='sudo pacman -S'
alias pacs='pacman -Ss'
alias u='sudo pacman -Syu'

# systemd
alias -- s+='sudo systemctl start'
alias -- s-='sudo systemctl stop'
alias    se='sudo systemctl enable'
alias    sd='sudo systemctl disable'
alias    sr='sudo systemctl restart'
alias    st='systemctl status'
