#!/bin/bash

t(){ test -z "$1" && tmux new || tmux attach }
mu () { mupdf "$@" & disown }
mpv() { /usr/bin/mpv "$1" &>/dev/null & disown }

rec() {
    ffmpeg -f x11grab -s 1366x768 -an -r 16 -loglevel quiet -i :0.0 -b:v 5M -y "$@" 
}

man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[01;31m")  \
        LESS_TERMCAP_md=$(printf "\e[00;33m")  \
        LESS_TERMCAP_us=$(printf "\e[01;31m")  \
        LESS_TERMCAP_me=$(printf "\e[0m")      \
        LESS_TERMCAP_se=$(printf "\e[0m")      \
        LESS_TERMCAP_ue=$(printf "\e[0m")      \
        man "$@"
}

cd() {
    if [ -n "$1" ]; then
        [ -d "$1" ] && { builtin cd "$1"; ls; } || builtin cd "$(dirname "$1")"
    else
        cd ~
    fi
}

cpf() {
   cp "$@" && cd "$_";
}

mvf() {
   mv "$@" && cd "$_";
}

mkdirf() {
   mkdir -p "$@" && cd "$_";
}

d(){ 
    case $1 in
        i) dtach -A /tmp/irssi.dtach irssi ;;
        r) dtach -A /tmp/rtorrent.dtach rtorrent ;;
        *) dtach -A /tmp/$1.dtach $1 ;;
    esac

}
touchpad(){
    local deviceid=$(xinput | grep TouchPad | cut -d "=" -f2| cut -f1)
    [ -z $deviceid ] && return 1
    val=$(xinput list-props $deviceid | grep able | tail -c 2)
    [ $(( ( $val + 1 ) % 2 )) -eq 0 ] && xinput --disable $deviceid \
                                      || xinput --enable $deviceid
}
asdf(){
    local file="$HOME/.playlist"
    [ -f $file ] || return 1
    [ -f "${file}.tmp" ] && rm -f "${file}.tmp" || echo "no temp file found"
    shuf -n $(wc -l $file | cut -d " " -f1) $file > "${file}.tmp"
    mpv --playlist="${file}.tmp"
}
swap(){
    mv $1 tmp.$1
    mv $2 $1
    mv tmp.$1 $2
}
sub(){
    if [[ -z "$1" ]]; then
        sublime & disown
    else
        sublime -n $@ &>/dev/null & disown
    fi
}

extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2) tar xvjf $1;;
            *.tar.gz) tar xvzf $1;;
            *.bz2) bunzip2 $1;;
            *.gz) gunzip $1;;
            *.tar) tar xvf $1;;
            *.tbz2) tar xvjf $1;;
            *.tgz) tar xvzf $1;;
            *.zip) unzip $1;;
            *.Z) uncompress $1;;
            *) echo "'$1' cannot be extracted via >extract<" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

soneeded() {
   readelf -d $1 | awk '/NEEDED/ {gsub(/[\[\]]/, "", $5); print $5}'
}

elfcompress() {
   [[ -n "$@" ]] || {
      echo "usage : elfcompress [binary]"
      return
   }

   cp "$@" /tmp/compress.temp
   strip -s -R .comment -R .gnu.version /tmp/compress.temp

   gzip -c /tmp/compress.temp > /tmp/compress.gz
   echo 'a=/tmp/I;tail -n+2 $0|zcat>$a;chmod +x $a;$a;rm $a;exit' >> /tmp/unpack.header

   cat /tmp/unpack.header /tmp/compress.gz > "$@.packed"
   chmod +x "$@.packed"

   rm /tmp/compress.temp
   rm /tmp/compress.gz
   rm /tmp/unpack.header
}
# vi:syntax=sh
