(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(require 'init-utils)
(require 'init-elpa)
(require 'init-themes)
(require 'init-gui-frames)
(require 'init-grep)
(require 'init-ibuffer)
(require 'init-dired)
(require 'init-flycheck)
(require 'init-recentf)
(require 'init-ido)
(require 'init-windows)
(require 'init-fonts)
(require 'init-git)
(require 'init-compile)
(require 'init-markdown)
(require 'init-javascript)
(require 'init-org)
(require 'init-html)
(require 'init-css)
(require 'init-evil)
(require 'init-misc)
(when (file-exists-p custom-file)
  (load custom-file))
(require 'init-locales)
(provide 'init)
